In [40]:
%matplotlib inline
from matplotlib import pyplot as plt
import seaborn as sns

In [41]:
import antipackage
import github.ellisonbg.misc.vizarray as va

In [42]:
import numpy as np

In [43]:
data = [0, 2, 4, 6]
a = np.array(data)

In [44]:
type(a)

numpy.ndarray

In [45]:
a

array([0, 2, 4, 6])

In [46]:
va.vizarray(a)

In [47]:
a.shape

(4,)

In [48]:
a.ndim

1

In [49]:
a.size

4

In [50]:
a.nbytes

32

In [51]:
a.dtype

dtype('int64')

In [57]:
data = [[0.0,2.0,4.0,6.0],[1.0,3.0,5.0,7.0]]
b = np.array(data)

In [58]:
b

array([[ 0.,  2.,  4.,  6.],
       [ 1.,  3.,  5.,  7.]])

In [59]:
va.vizarray(b)

In [60]:
b.shape, b.ndim, b.size, b.nbytes

((2, 4), 2, 8, 64)

In [61]:
c = np.arange(0.0, 10.0, 1.0)
c

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

In [62]:
e = np.linspace(0.0, 5.0, 11)
e

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [63]:
np.empty

<function numpy.core.multiarray.empty>

In [64]:
np.zeros((3, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [65]:
np.ones((3, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [66]:
a = np.array([0, 1, 2, 3])

In [67]:
a, a.dtype

(array([0, 1, 2, 3]), dtype('int64'))

In [68]:
b = np.zeros((2, 2), dtype = np.complex64)

In [69]:
c = np.arange(0, 10, 2, dtype = np.float)
c

array([ 0.,  2.,  4.,  6.,  8.])

In [70]:
d = c.astype(dtype = np.int)

In [71]:
np.float*?

In [72]:
a = np.empty((3,3))
a.fill(0.1)
a

array([[ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1],
       [ 0.1,  0.1,  0.1]])

In [73]:
b = np.ones((3,3))
b

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [75]:
a + b

array([[ 1.1,  1.1,  1.1],
       [ 1.1,  1.1,  1.1],
       [ 1.1,  1.1,  1.1]])

In [76]:
b / a

array([[ 10.,  10.,  10.],
       [ 10.,  10.,  10.],
       [ 10.,  10.,  10.]])

In [78]:
a ** 2

array([[ 0.01,  0.01,  0.01],
       [ 0.01,  0.01,  0.01],
       [ 0.01,  0.01,  0.01]])

In [79]:
np.pi * b

array([[ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265],
       [ 3.14159265,  3.14159265,  3.14159265]])

In [80]:
a = np.random.rand(10, 10)

In [81]:
va.enable

<function github.ellisonbg.misc.vizarray.enable>

In [82]:
a

array([[ 0.06042759,  0.82013966,  0.20923969,  0.82298253,  0.39777137,
         0.16697057,  0.04840525,  0.23235343,  0.05670063,  0.89884396],
       [ 0.12870561,  0.9150747 ,  0.51818695,  0.31086148,  0.53228308,
         0.63529253,  0.9676085 ,  0.03045213,  0.65915349,  0.40700536],
       [ 0.8439568 ,  0.94820609,  0.3254754 ,  0.65060662,  0.57249243,
         0.81023562,  0.90328015,  0.55998516,  0.53926775,  0.42595367],
       [ 0.17024377,  0.64445812,  0.05133403,  0.70428481,  0.73077548,
         0.92033752,  0.39276949,  0.23240558,  0.25952686,  0.21507777],
       [ 0.0811034 ,  0.20740161,  0.33901776,  0.95946552,  0.72580022,
         0.27755957,  0.79775125,  0.78949877,  0.40720512,  0.60632164],
       [ 0.2554695 ,  0.16763672,  0.2923767 ,  0.5206425 ,  0.23372713,
         0.89713344,  0.76508931,  0.07417076,  0.72614281,  0.54217027],
       [ 0.34992143,  0.94686597,  0.61246075,  0.09645634,  0.06365613,
         0.63373767,  0.49652203,  0.31006348

In [83]:
a[0,0]

0.060427589208566168

In [84]:
a[-1, -1] == a[9, 9]

True

In [86]:
a[:,0]

array([ 0.06042759,  0.12870561,  0.8439568 ,  0.17024377,  0.0811034 ,
        0.2554695 ,  0.34992143,  0.04810715,  0.04717436,  0.5604671 ])

In [87]:
a[-1, :]

array([ 0.5604671 ,  0.91342881,  0.61635751,  0.21843716,  0.00197656,
        0.70564673,  0.6618094 ,  0.55786198,  0.58353724,  0.36190531])

In [89]:
a[0:2, 0:2]

array([[ 0.06042759,  0.82013966],
       [ 0.12870561,  0.9150747 ]])

In [90]:
a[0:5, 0:5] = 1.0

In [91]:
a

array([[ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.16697057,  0.04840525,  0.23235343,  0.05670063,  0.89884396],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.63529253,  0.9676085 ,  0.03045213,  0.65915349,  0.40700536],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.81023562,  0.90328015,  0.55998516,  0.53926775,  0.42595367],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.92033752,  0.39276949,  0.23240558,  0.25952686,  0.21507777],
       [ 1.        ,  1.        ,  1.        ,  1.        ,  1.        ,
         0.27755957,  0.79775125,  0.78949877,  0.40720512,  0.60632164],
       [ 0.2554695 ,  0.16763672,  0.2923767 ,  0.5206425 ,  0.23372713,
         0.89713344,  0.76508931,  0.07417076,  0.72614281,  0.54217027],
       [ 0.34992143,  0.94686597,  0.61246075,  0.09645634,  0.06365613,
         0.63373767,  0.49652203,  0.31006348

In [93]:
va.disable()

In [97]:
ages = np.array([23, 56,67, 89, 23, 56, 27, 12, 8, 72])
genders = np.array(['m', 'm', 'f', 'f', 'm', 'f', 'm' ,'m', 'm', 'f'])

In [98]:
ages > 30

array([False,  True,  True,  True, False,  True, False, False, False,  True], dtype=bool)

In [99]:
genders == 'm'

array([ True,  True, False, False,  True, False,  True,  True,  True, False], dtype=bool)

In [100]:
(ages > 10) & (ages < 50)

array([ True, False, False, False,  True, False,  True,  True, False, False], dtype=bool)

In [101]:
mask = (genders == 'f')
ages[mask]

array([67, 89, 56, 72])

In [102]:
ages[ages>30]

array([56, 67, 89, 56, 72])

In [104]:
va.enable()

In [105]:
a = np.random.rand(3,4)

In [106]:
a

array([[ 0.13951964,  0.20878384,  0.23868772,  0.24337142],
       [ 0.51842151,  0.14363269,  0.9708378 ,  0.39098427],
       [ 0.82449074,  0.5398611 ,  0.16165859,  0.00788175]])

In [107]:
a.T

array([[ 0.13951964,  0.51842151,  0.82449074],
       [ 0.20878384,  0.14363269,  0.5398611 ],
       [ 0.23868772,  0.9708378 ,  0.16165859],
       [ 0.24337142,  0.39098427,  0.00788175]])

In [ ]:
a.reshape(6,2)

In [ ]:
a.ravel()

In [ ]:
va.disable