# Numpy Exercise 1

## Imports

In [1]:
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
import antipackage
import github.ellisonbg.misc.vizarray as va

Downloading:  https://raw.githubusercontent.com/ellisonbg/misc/master/vizarray.py
Using existing version:  github.ellisonbg.misc.vizarray


## Checkerboard

Write a Python function that creates a square `(size,size)` 2d Numpy array with the values `0.0` and `1.0`:

* Your function should work for both odd and even `size`.
* The `0,0` element should be `1.0`.
* The `dtype` should be `float`.

In [3]:
va.enable()

In [14]:
def checkerboard(size):
    # if size is even
    if size %2 == 0:
        # if the row is odd produce the pattern 0,1 then repeate half as many times as size
        odd = (size/2) * [0,1]
        # if the row is even produce the pattern 1,0 then repeate half as many times as size
        even = (size/2) * [1,0]
        #stack the odd and even rows on top of each other and put in to array that is (size,size)
        board = np.row_stack((size/2)/1*(odd, even))
    
    # if size is odd and 5 or larger
    elif size >4 and size %2 == 1:
        # if the row is odd produce the pattern 0,1 then repeate half as many times as size - 1 than add a 0 at the end 
        odd = ((size/2)) * [0,1] +[0]
        # if the row is even produce the pattern 1,0 then repeate half as many times as size - 1 than add a 1 at the end
        even = ((size/2)) * [1,0] + [1]
        #stack the odd and even rows on top of each other and put in to array that is (size-1, size)
        x_board = np.row_stack((size/2)/1*(odd, even))
        # if the row is odd produce the pattern 0,1 then repeate half as many times as size - 1 than add a 0 at the end 
        x_odd = ((size/2)) * [0,1] +[0]
         #stack the board x_odd row producing an array that is (size,size)
        board = np.row_stack((size/4)/1*(x_board, x_odd))
    elif size == 1:
        board = [0]
        
    elif size == 3:
        odd = [0,1,0] 
        even = [1,0,1]
        board = np.row_stack((size/3)/1*(odd, even, odd))
    return board       

print checkerboard(10)


[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


In [15]:
va.vizarray(checkerboard(10)) 

In [17]:
# a = checkerboard(4)
# assert a[0,0]==1.0
# assert a.sum()==8.0
# assert a.dtype==np.dtype(float)
# assert np.all(a[0,0:5:2]==1.0)
# assert np.all(a[1,0:5:2]==0.0)

b = checkerboard(5)
assert b[0,0]==1.0
assert b.sum()==13.0
assert np.all(b.ravel()[0:26:2]==1.0)
assert np.all(b.ravel()[1:25:2]==0.0)

AssertionError: 

Use `vizarray` to visualize a checkerboard of `size=20` with a block size of `10px`.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
assert True

Use `vizarray` to visualize a checkerboard of `size=27` with a block size of `5px`.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
assert True

In [4]:
def checkerboard(w, h) :
    re = np.r_[ w*[0,1] ]
    ro = np.r_[ w*[1,0] ]
    return np.row_stack(h*(re, ro))


AB = checkerboard(5, 10)

In [8]:
va.enable()

In [29]:
def gen_checkerboard(size):
    even = 1 * [0,1]
    odd = 1* [1,0]
    checkerboard = np.row_stack(size/2*(even, odd))
    return checkerboard.repeat(size, axis = 0)
print (gen_checkerboard(2))

[[0 1]
 [0 1]
 [1 0]
 [1 0]]
